### ISSUE TITLE
Handle multiple slots on yubikey

### ISSUE THREAD

**Issue by MeneDev** [MeneDev/yubi-oath-vpn#11]
It's currently unclear which slots are used

**Comment by Faradax** [comment]
I'd like to address this issue, because we want to use more slots on our yubikeys.

I suggest adding a configuration parameter for specifying the slot _by name_ as the index seems to change. We suspect they are sorted alphabetically. Can you confirm this?

Do you have any pointers on where to look in the code base for the selection of the slot?

**Comment by MeneDev** [comment]
Thanks for your interest!

This is the function that is supposed to do this kind of filtering:

https://github.com/MeneDev/yubi-oath-vpn/blob/ca0f212dfc52f91d234686b5b52ad3c790f17037/cmd/yubi-oath-vpn/yubi-oath-vpn.go#L117

You'll probably need to pass additional parameters that you read from the flags.

A bigger problem will be identifying the yubikey. There is a serial number and a function to receive it is implemented here:

https://github.com/MeneDev/yubi-oath-vpn/blob/ca0f212dfc52f91d234686b5b52ad3c790f17037/yubikey/scard/scard_yubikey.go#L251

I think you need to call this first:
https://github.com/MeneDev/yubi-oath-vpn/blob/ca0f212dfc52f91d234686b5b52ad3c790f17037/yubikey/scard/scard_yubikey.go#L64

I would extend the `YubiKey` interface with an appropriate function to receive the serial.
https://github.com/MeneDev/yubi-oath-vpn/blob/ca0f212dfc52f91d234686b5b52ad3c790f17037/yubikey/yubikey.go#L5

That would allow you to receive the serial in `applicableYubiKey` from the `key` parameter

**Comment by lakner** [comment]
Thanks for looking at this! 

The problem we're having right now isn't about supporting two separate Yubikeys, it's about using more than one slot on the same Yubikey and selecting the correct one for the VPN connection (and not some slot that is being used for 2FA authentication somewhere else). 

I've been looking into this and it seems that the information for all slots is already being read here: 
https://github.com/MeneDev/yubi-oath-vpn/blob/e11a6020efe2484bfb51c4fcefa0a9594c504084/yubikey/scard/scard_yubikey.go#L263-L291

Only the information for the last slot is is returned, though. `tag` contains either 'q' or 'd'. `tlvs[q]` contains a string identifying the slot, `tlvs[d]` some data that's used to get the code. When `tlvs[q]` and `tlvs[d]` are written for a new slot, it overwrites the data from the previous slot.

The function needs to return the data for all the slots instead of just the last one.  Then we can choose which one to use with a new command line parameter or something similar.

**Comment by MeneDev** [comment]
Oh, you're right, sorry for the misunderstanding. I've never investigated the different slots on a yubikey, but your conclusions sound plausible to me. Feel free to change the interface as you see fit!

**Comment by MeneDev** [comment]
Released in v0.6.0 https://github.com/MeneDev/yubi-oath-vpn/releases/tag/v0.6.0
Thanks for contributing!
